import { Geist, Geist_Mono } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import LandingHeader from "./_compnents/landingHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Expense Tracker",
  description: "Generated by create next app",
  icons : {
    icon : "/favlogo.png"
  },
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-gray-900 dark:text-white`}> 
    <Toaster /> {/* Alert message */}

    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      signInForceRedirectUrl="/dashboard"
      signInFallbackRedirectUrl="/dashboard"
      afterSignOutUrl={process.env.NEXT_PUBLIC_CLERK_AFTER_SIGN_OUT_URL}>
        
      <div>
        <LandingHeader />
        {children}
      </div>  

    </ClerkProvider>

    </body>
    </html>
  );
}
